import MapObject from "@/types/MapObject";

export const Spawn: MapObject = {
  mapName: "Spawn",
  mapSrc: "/housemap.png",
  textures: [
    {
      src: "/house.png",
      pxOff: 40,
      pyOff: -5,
      filledCells: [
        [11, -5],
        [12, -5],
        [13, -5],
        [14, -5],
        [15, -5],
        [15, -4],
        [15, -3],
        [15, -2],
        [15, 0],
        [10, -4],
        [9, -3],
        [8, -3],
        [7, -3],
        [7, -2],
        [6, -1],
        [6, 0],
        [5, 1],
        [5, 2],
        [4, 3],
        [5, 3],
        [6, 3],
        [7, 3],
        [8, 3],
        [9, 3],
        [10, 3],
        [11, 3],
        [12, 3],
        [14, 1],
        [13, 2],
        [13, -1],
        [14, 0],
        [14, -2],
      ],
      interactiveCells: [],
      renderCells: [
        [11, -5],
        [12, -5],
        [13, -5],
        [14, -5],
        [15, -5],
        [15, -4],
        [15, -3],
        [15, -2],
        [15, 0],
        [10, -6],
        [16, 0],
        [17, 1],
      ],
    },
    {
      src: "/kitty.png",
      pxOff: 164,
      pyOff: 81,
      filledCells: [[16, 0]],
      interactiveCells: [
        {
          cell: [16, 0],
          interaction: "kitty",
        },
      ],
      renderCells: [[16, 0]],
    },
    {
      src: "/mailbox.png",
      pxOff: 198,
      pyOff: 78,
      filledCells: [[18, 1]],
      interactiveCells: [
        {
          cell: [18, 1],
          interaction: "mailbox",
        },
      ],
      renderCells: [[18, 1]],
    },
    {
      src: "/bushes.png",
      pxOff: 120,
      pyOff: 89,
      filledCells: [
        [16, -4],
        [16, -3],
      ],
      interactiveCells: [
        {
          cell: [16, -4],
          interaction: "bushes",
        },
        {
          cell: [16, -3],
          interaction: "bushes",
        },
      ],
      renderCells: [
        [16, -4],
        [16, -3],
      ],
    },
  ],
  width: 310,
  height: 164,
};
