import MapObject from "@/types/MapObject";

export const Spawn: MapObject = {
  mapName: "Spawn",
  mapSrc: "/housemap.png",
  textures: [
    {
      src: "/house.png",
      pxOff: 40,
      pyOff: -5,
      filledCells: [
        [11, -5],
        [12, -5],
        [13, -5],
        [14, -5],
        [15, -5],
        [15, -4],
        [15, -3],
        [15, -2],
        [15, 0],
        [10, -4],
        [9, -3],
        [8, -3],
        [7, -3],
        [7, -2],
        [6, -1],
        [6, 0],
        [5, 1],
        [5, 2],
        [4, 3],
        [5, 3],
        [6, 3],
        [7, 3],
        [8, 3],
        [9, 3],
        [10, 3],
        [11, 3],
        [12, 3],
        [14, 1],
        [13, 2],
        [13, -1],
        [14, 0],
        [14, -2],
      ],
      interactiveCells: [],
      renderCells: [
        [11, -5],
        [12, -5],
        [13, -5],
        [14, -5],
        [15, -5],
        [15, -4],
        [15, -3],
        [15, -2],
        [15, 0],
        [10, -6],
        [16, 0],
        [17, 1],
      ],
    },
    {
      src: "/kitty.png",
      pxOff: 164,
      pyOff: 81,
      filledCells: [[16, 0]],
      interactiveCells: [
        {
          cell: [16, 0],
          interaction: "kitty",
        },
      ],
      renderCells: [[16, 0]],
    },
    {
      src: "/mailbox.png",
      pxOff: 198,
      pyOff: 78,
      filledCells: [[18, 1]],
      interactiveCells: [
        {
          cell: [18, 1],
          interaction: "mailbox",
        },
      ],
      renderCells: [[18, 1]],
    },
    {
      src: "/bushes.png",
      pxOff: 120,
      pyOff: 89,
      filledCells: [
        [16, -4],
        [16, -3],
      ],
      interactiveCells: [
        {
          cell: [16, -4],
          interaction: "bushes",
        },
        {
          cell: [16, -3],
          interaction: "bushes",
        },
      ],
      renderCells: [
        [16, -4],
        [16, -3],
      ],
    },
  ],
  width: 310,
  height: 164,
};

export const Bayou: MapObject = {
  mapName: "Bayou",
  mapSrc: "/bayou/map.png",
  textures: [
    {
      src: "/bayou/backwall.png",
      pxOff: 70,
      pyOff: 15,
      filledCells: [
        [9, -3],
        [9, -2],
        [9, -1],
        [9, 0],
        [9, 1],
        [9, 2],
      ],
      interactiveCells: [],
      renderCells: [
        [9, -3],
        [9, -2],
        [9, -1],
        [9, 0],
        [9, 1],
        [9, 2],
      ],
    },
    {
      src: "/bayou/rightwall.png",
      pxOff: 110,
      pyOff: 15,
      filledCells: [
        [12, 1],
        [13, 1],
        [14, 1],
        [15, 1],
        [16, 1],
        [17, 1],
        [12, 2],
        [11, 3],
        [10, 3],
      ],
      interactiveCells: [],
      renderCells: [
        [10, 1],
        [11, 1],
        [12, 1],
        [13, 1],
        [14, 1],
        [15, 1],
        [16, 1],
        [17, 1],
      ],
    },
    {
      src: "/bayou/backdesk.png",
      pxOff: 70,
      pyOff: 58,
      filledCells: [
        [10, -3],
        [11, -3],
      ],
      interactiveCells: [],
      renderCells: [
        [10, -3],
        [11, -3],
      ],
    },
    {
      src: "/bayou/frontdesk.png",
      pxOff: 130,
      pyOff: 73,
      filledCells: [
        [16, -3],
        [16, -2],
        [16, -1],
        [16, 0],
      ],
      interactiveCells: [],
      renderCells: [
        [16, -3],
        [16, -2],
        [16, -1],
        [16, 0],
      ],
    },
    {
      src: "/bayou/counter.png",
      pxOff: 60,
      pyOff: 40,
      filledCells: [
        [11, -4],
        [12, -4],
        [10, -4],
        [16, -4],
        [14, -4],
        [15, -4],
        [17, -4],
        [17, -3],
        [17, -2],
        [17, -1],
        [17, 0],
      ],
      interactiveCells: [],
      renderCells: [
        [10, -4],
        [11, -4],
        [17, 0],
        [17, -1],
        [17, -2],
        [17, -3],
        [17, -4],
        [16, -4],
        [15, -4],
        [14, -4],
        [12, -4],
      ],
    },
    {
      src: "/bayou/doors.png",
      pxOff: 40,
      pyOff: 40,
      filledCells: [
        [11, -7],
        [11, -6],
        [11, -5],
        [12, -8],
        [13, -8],
        [14, -8],
        [15, -8],
        [16, -8],
        [17, -8],
        [18, -8],
        [19, -8],
        [20, -8],
        [21, -7],
        [21, -6],
        [21, -5],
        [21, -4],
        [21, -3],
        [21, -2],
        [21, -1],
        [21, 0],
        [21, 1],
        [20, 2],
        [18, 2],
        [19, 2],
      ],
      interactiveCells: [],
      renderCells: [
        [11, -7],
        [11, -6],
        [11, -5],
      ],
    },
  ],
  width: 270,
  height: 169,
};
